//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já cadastrado.
        /// </summary>
        internal static string AlreadyEamilError {
            get {
                return ResourceManager.GetString("AlreadyEamilError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não encontrado.
        /// </summary>
        internal static string CustomerNotFoundError {
            get {
                return ResourceManager.GetString("CustomerNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to olá {0}, seu código de verificação é {1}..
        /// </summary>
        internal static string EmailBodyKey {
            get {
                return ResourceManager.GetString("EmailBodyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para recuperar a senha, acesse o link {0}.
        /// </summary>
        internal static string EmailBodyRecover {
            get {
                return ResourceManager.GetString("EmailBodyRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não encontrado.
        /// </summary>
        internal static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha invalidos.
        /// </summary>
        internal static string EmailPassInvalidError {
            get {
                return ResourceManager.GetString("EmailPassInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao enviar o e-mail.
        /// </summary>
        internal static string EmailSendError {
            get {
                return ResourceManager.GetString("EmailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificação.
        /// </summary>
        internal static string EmailSubjectKey {
            get {
                return ResourceManager.GetString("EmailSubjectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de senha.
        /// </summary>
        internal static string EmailSubjectRecover {
            get {
                return ResourceManager.GetString("EmailSubjectRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem vindo!.
        /// </summary>
        internal static string EmailSubjectWelcome {
            get {
                return ResourceManager.GetString("EmailSubjectWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem vindo!.
        /// </summary>
        internal static string EmailWlcomeBody {
            get {
                return ResourceManager.GetString("EmailWlcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao {0}, favor tente novamente mais tarde.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
    }
}
